server:
  port: 8083

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/**
            - Method=GET,POST

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8089/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

#okta configuration
okta:
  oauth2:
    issuer: https://dev-64830898.okta.com/oauth2/default
    audience: api://default
    client-id: 0oahlvj1owd7onMla5d7
    client-secret: d99c0fvweN8_bkBv9dlyNaBWbjTWzaZBUAXn_x1V4j5WA0ZqbC-3ATlKI-y7pb8h
    scopes: open, profile, offline_access
