
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8089/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ayushi3259/microservice-config.git
          clone-on-start: true
