server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rating
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import: configserver:http://localhost:9000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect



